//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dosen_wali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dosen_wali()
        {
            this.mahasiswas = new HashSet<mahasiswa>();
        }
    
        public int id { get; set; }
        public string nidn { get; set; }
        public string nama_dosen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mahasiswa> mahasiswas { get; set; }
    }
}
